/* Generated By:JavaCC: Do not edit this line. CalculatorConstants.java */

/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface CalculatorConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int NUMBER = 4;
  /** RegularExpression Id. */
  int DIGIT = 5;
  /** RegularExpression Id. */
  int EOL = 6;
  /** RegularExpression Id. */
  int TANIMLA = 7;
  /** RegularExpression Id. */
  int YAZDIR = 8;
  /** RegularExpression Id. */
  int STR = 9;
  /** RegularExpression Id. */
  int LETTER = 10;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\r\"",
    "\"\\t\"",
    "<NUMBER>",
    "<DIGIT>",
    "\"\\n\"",
    "\"tanimla\"",
    "\"yazdir\"",
    "<STR>",
    "<LETTER>",
    "\"(\"",
    "\")\"",
    "\"=\"",
    "\"+\"",
    "\"-\"",
    "\"*\"",
    "\"/\"",
  };

}
